name: Build Resume

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - run: nix develop -c './generate.sh'

      - uses: actions/upload-artifact@v4
        with:
          name: resume
          path: resume.pdf
