name: Update Resume

on:
  push:
    branches:
      - main

environment: Main branch

jobs:
  build:
    uses: ./.github/workflows/build.yml

  update:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: resume
          path: resume.pdf

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update resume
          file_pattern: resume.pdf
