name: Build and Update Resume

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    environment: Main branch
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: generate.sh
        run: |
          if [[ $RUNNER_DEBUG ]]; then
            nix develop -c -- bash -x ./generate.sh
          else
            nix develop -c ./generate.sh
          fi

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update resume
          file_pattern: resume.pdf
